#!/bin/bash

#SBATCH -o logs/WDM7_SLURM.out
#SBATCH -e logs/WDM7_SLURM.err
#SBATCH -t 24:00:00
#SBATCH -J WDM7-Europe
#SBATCH -p long
#SBATCH -N 4 --ntasks-per-node=20

NAMELIST=/home/mda_silv/github_projects/shell/ictp/regcm_exp/eur_11/EUR-11_WDM7.in
BINARIES=/home/mda_silv/RegCM/bin/
EXTENSION=CLM45

# load required modules
module purge
source /opt-ictp/ESMF/env202108
export OMP_NUM_THREADS=20

# run model
set -e
{
  mpirun $BINARIES/regcmMPI$EXTENSION $NAMELIST
}
