'reinit'
'sdfopen mask_CAM.nc'
'set lat -1.5 43.5'
'set lon -121 -22'
'set gxout fwrite'
'set fwrite -le mask_CAM.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
