'reinit'
'sdfopen mask_AUS.nc'
'set lat -52 -1'
'set lon -89 179'
'set gxout fwrite'
'set fwrite -le mask_AUS.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
