'reinit'
'sdfopen mask_WAS.nc'
'set lat -15.75 45.75'
'set lon 19.25 115.25'
'set gxout fwrite'
'set fwrite -le mask_WAS.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
