'reinit'
'sdfopen mask_NAM.nc'
'set lat 30.5 75.5'
'set lon -131.5 -53.5'
'set gxout fwrite'
'set fwrite -le mask_NAM.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
