'reinit'
'sdfopen mask_EAS.nc'
'set lat -15.75 66.75'
'set lon 77 159.5'
'set gxout fwrite'
'set fwrite -le mask_EAS.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
