'reinit'
'sdfopen mask_AFR.nc'
'set lat -40 -1'
'set lon -20 59.5'
'set gxout fwrite'
'set fwrite -le mask_AFR.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
