'reinit'
'sdfopen mask_SAM.nc'
'set lat -56 -14'
'set lon -93 -30'
'set gxout fwrite'
'set fwrite -le mask_SAM.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
