'reinit'
'sdfopen mask_EUR.nc'
'set lat 28 67'
'set lon -12 36'
'set gxout fwrite'
'set fwrite -le mask_EUR.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
