'reinit'
'sdfopen mask_CAM.nc'
'set lat 0 33'
'set lon -121 -28'
'set gxout fwrite'
'set fwrite -le mask_CAM.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'quit'
