#!/bin/bash

#SBATCH -A ICT23_ESP_1
#SBATCH -p dcgp_usr_prod
#SBATCH -N 16
#SBATCH --ntasks-per-node=112
#SBATCH -t 1-00:00:00
#SBATCH -o logs/SAM-3km_SLURM.out
#SBATCH -e logs/SAM-3km_SLURM.err
#SBATCH -J SAM-3km
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=mda_silv@ictp.it

{
set -eo pipefail

# load required modules
# module purge
source /leonardo/home/userexternal/ggiulian/modules

NAMELIST=/leonardo/home/userexternal/mdasilva/github_projects/shell/ictp/regcm_exp/sam_3km/ERA5_SAM-3km.in
BINARIES=/leonardo/home/userexternal/mdasilva/github_projects/shell/ictp/regcm_exp/sam_3km/bin/
EXTENSION=CLM45

# run model
mpirun $BINARIES/regcmMPI$EXTENSION $NAMELIST
}
