#!/bin/bash

#SBATCH -A ICT25_ESP
#SBATCH -p dcgp_usr_prod
#SBATCH -N 16 
#SBATCH --ntasks-per-node=112
#SBATCH -t 1-00:00:00
#SBATCH -o logs/NoTo-CTRL.out
#SBATCH -e logs/NoTo-CTRL.err
#SBATCH -J CTRL
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=mda_silv@ictp.it

{
# load required modules
# module purge
source /leonardo/home/userexternal/ggiulian/modules
set -eo pipefail

NAMELIST=/leonardo/home/userexternal/mdasilva/github_projects/shell/ictp/regcm_exp/eur_11/SAM-22_RegCM5-ERA5_ctrl.in
BINARIES=/leonardo/home/userexternal/ggiulian/RegCM/bin/
EXTENSION=CLM45

# run model
mpirun $BINARIES/regcmMPI$EXTENSION $NAMELIST
}
