#!/bin/bash

#SBATCH -J sam_3km
#SBATCH -A ICT23_ESP
#SBATCH -p skl_usr_prod
#SBATCH --qos=qos_prio
#SBATCH -t 24:00:00
#SBATCH -N 1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mda_silv@ictp.it

module purge
source /marconi/home/userexternal/ggiulian/STACK22/env2022

PLATFORM=SKL
export OMP_NUM_THREADS=48
REGCM=/marconi/home/userexternal/mdasilva/bin
SUFFIX=CLM45_${PLATFORM}
NAMELIST=/marconi/home/userexternal/mdasilva/github_projects/shell/regcm_ictp/regcm_exp/sam_3km/SAM_3km_CP_RegCM5_ERA5.in

# load required modules

export I_MPI_FABRICS=shm:tmi
export I_MPI_TMI_PROVIDER=psm2
OUTFILE=/marconi/home/userexternal/mdasilva/github_projects/shell/regcm_ictp/regcm_exp/sam_3km/ICBC.out
ERRFILE=/marconi/home/userexternal/mdasilva/github_projects/shell/regcm_ictp/regcm_exp/sam_3km/ICBC.err

${REGCM}/terrain${SUFFIX}    ${NAMELIST} >> ${OUTFILE} 2> ${ERRFILE}
${REGCM}/mksurfdata${SUFFIX} ${NAMELIST} >> ${OUTFILE} 2> ${ERRFILE}
${REGCM}/sst${SUFFIX}        ${NAMELIST} >> ${OUTFILE} 2> ${ERRFILE}
${REGCM}/icbc${SUFFIX}       ${NAMELIST} >> ${OUTFILE} 2> ${ERRFILE}
