# -*- coding: utf-8 -*-
"""MOAAP_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sD2EsaH34M-rZo1U3w988X46tXBV3OCy
"""



"""## **Multi-Object Analysis of Atmospheric Phenomena (MOAAP) Tutorial**

> This notebook allows you to run the MOAAP algorithm on an example dataset and visualize its output. The configuration of MOAAP is the same as in [Prein et al. (2023)](https://essopenarchive.org/users/489196/articles/621516-the-multi-scale-interactions-of-atmospheric-phenomenon-in-extreme-and-mean-precipitation) including the input data except that only 24-hours of data are loaded due to memory restrictions in Google Colaboratory. The short time period does not allow to classify equatorial waves.

The tutorial is intended to lower the barrier of running MOAAP by showcasing the format of its input variables and the analysis and visualization of its output.

The notebook runs through the following steps:


1.   Load and install Python packages
2.   Get the latest version of MOAAP from [github](https://github.com/andreas-prein/MOAAP/)
3.   Get example data from Google Drive to run MOAAP
4.   Read and visualize MOAAP output

More information about the MOAAP algorithm can be found on the [MOAAP wiki](https://github.com/AndreasPrein/MOAAP/wiki) and in [Prein et al. (2023)](https://essopenarchive.org/users/489196/articles/621516-the-multi-scale-interactions-of-atmospheric-phenomenon-in-extreme-and-mean-precipitation). A video that introduces this tutorial is available on [Youtube](https://youtu.be/K5XkHX--sqY).

The entire MOAAP dataset, as it is published in [Prein et al. (2023)](https://essopenarchive.org/users/489196/articles/621516-the-multi-scale-interactions-of-atmospheric-phenomenon-in-extreme-and-mean-precipitation) can be downloaded from [this Globus endpoint](https://app.globus.org/file-manager?origin_id=55272495-04a8-4486-a07f-eb21ca21797c&origin_path=%2F).

For questions and feedback please contact Andreas F. Prein (prein@ucar.edu).

### 1) Load and install Python packages
"""

import xarray as xr
#!pip install netCDF4
import netCDF4
#!pip install cartopy
import cartopy
import numpy as np
import pandas as pd
#!pip install metpy
import metpy
import warnings
warnings.filterwarnings("ignore")
from tqdm import tqdm

"""### 2) Get the latest version of MOAAP from github

"""

#!git clone https://github.com/andreas-prein/MOAAP.git

#!mv "MOAAP/Tracking_Functions.py" "."
from Tracking_Functions import moaap

"""### 3) Get example data from Google Drive to run MOAAP

"""

#!gdown 1hD9hD3c9rBhcTN-c5FN87l0pHp_SCscE

data_vars = xr.open_dataset('20000101-04_MOAAP-Input_24h.nc')

dT = 1 # time interval of input files [hours]
Mask = np.copy(data_vars['xlon']); Mask[:]=1 # tracking is applied globally
DataName = 'ERA5'
OutputFolder = 'moaap_output/'
#!mkdir $OutputFolder
time_datetime = pd.to_datetime(np.array(data_vars['time'].values, dtype='datetime64'))

object_split = moaap(
                      data_vars['xlon'],
                      data_vars['xlat'],
                      time_datetime,
                      dT,
                      Mask,
                      v850 = None,
                      u850 = None,
                      t850 = None,
                      q850 = None,
                      slp  = None,
                      ivte = None,
                      ivtn = None,
                      z500 = None,
                      v200 = None,
                      u200 = None,
                      pr   = np.array(data_vars['pr']),
                      tb   = np.array(data_vars['Tb']),
                      DataName = DataName,
                      OutputFolder = OutputFolder,
                      js_min_anomaly = 12,
                      MinTimeJS = 12,
                        )

"""### 4) Read and visualize MOAAP output"""

data_moaap = xr.open_dataset('moaap_output/20000101_ERA5_ObjectMasks__dt-1h_MOAAP-masks.nc')

# load MCS characteristics
import pickle
with open('moaap_output/MCSs_200001__dt-1h_MOAAP-masks.pkl', 'rb') as f:
    mcs_charac = pickle.load(f)

import cartopy.crs as ccrs
import matplotlib.pyplot as plt

# Create a figure and axis with a PlateCarree projection (latitude and longitude)
fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()},
                       figsize=(14,6))

# Set the extent of the map (in this case, the entire globe)
ax.set_extent([-180, 180, -90, 90], crs=ccrs.PlateCarree())

# Add coastlines and gridlines for reference
ax.coastlines(color='#969696')
ax.gridlines()

# Generate some random data (latitude, longitude, and values)
mcs_mask = np.array(data_moaap['MCS_Tb_Objects'][12,:,:])
mcs_mask[mcs_mask == 0] = np.nan
sc = plt.pcolormesh(data_moaap['lon'],
                    data_moaap['lat'],
                    mcs_mask,
                    cmap = 'nipy_spectral')


# plot MCS tracks
for ii in range(len(mcs_charac.keys())):
  LatLonTrack = mcs_charac[list(mcs_charac.keys())[ii]]['track']
  plt.plot(LatLonTrack[:,1],LatLonTrack[:,0], transform=ccrs.PlateCarree(), lw=1, color='k')

ax.set_extent([-180, 180, -70, 70], crs=ccrs.PlateCarree())

# Add a colorbar to the plot
cbar = plt.colorbar(sc, ax=ax, orientation='vertical', shrink=0.7, label='MCS mask')

# Set the title of the plot
plt.title('MCS tracks (black lines) and masks at '+str(time_datetime[12])[:16])

# Show the plot
plt.show()

import matplotlib.gridspec as gridspec
fig = plt.figure(figsize=(15,4))
gs1 = gridspec.GridSpec(1,3)
gs1.update(left=0.01, right=0.98,
           bottom=0.1, top=0.95,
           wspace=0.2, hspace=0.2)

obj = '1'

# MCS anvile size
ax = plt.subplot(gs1[0,0])
plt.title('Development of anvil size of MCS #' + obj)
plt.plot(mcs_charac[obj]['times'], mcs_charac[obj]['size']/1000**2)

ax.set_xlabel('time [hours]')
plt.xticks(rotation=45)
ax.set_ylabel('MCS anvil size [km$^2$]')

# MCS volume precipitation
ax = plt.subplot(gs1[0,1])
plt.title('Precipitation volume of MCS #' + obj)
plt.plot(mcs_charac[obj]['times'], mcs_charac[obj]['tot'])
ax.set_xlabel('time [hours]')
plt.xticks(rotation=45)
ax.set_ylabel('precipitation volume [km$^{3}$ h$^{-1}$]')

# MCS maximum precipitation
ax = plt.subplot(gs1[0,2])
plt.title('Max. precipitation of MCS #' + obj)
plt.plot(mcs_charac[obj]['times'], mcs_charac[obj]['max'])
ax.set_xlabel('time [hours]')
plt.xticks(rotation=45)
ax.set_ylabel('precipitation [mm h$^{-1}$]')

# Show the plot
plt.show()

object_names = [['cold clouds', '#737373', '-', 2],
                ['surface cyclones', 'k', '-', 2],
                ['mid-level cyclones', 'k', '--', 2],
                ['anticyclones', '#ff7f00', '-', 2],
                ['MCS', '#33a02c', '-', 2],
                ['moisture streams', 'r', '-', 2],
                ['jets', '#6a3d9a', '-', 2],
                ['Rossby waves', '#8c510a', '-', 3],
                ['mixed Rossby gravity waves', '#bf812d', '-', 1.5],
                ['inertia gravity waves', '#dfc27d','-', 3],
                ['Kelvin waves', '#abd9e9','-', 1.5],
                ['eastward inertia gravity waves', '#4575b4', '-', 3],
                ['fronts', '#cab2d6', '-', 2]]

#!mkdir 'images'

for tt in tqdm(range(len(time_datetime))):

    # Create a figure and axis with a PlateCarree projection (latitude and longitude)
    fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()},
                          figsize=(14,6))

    # Set the extent of the map (in this case, the entire globe)
    # ax.set_extent([-180, 180, -90, 90], crs=ccrs.PlateCarree())

    # Add coastlines and gridlines for reference
    ax.coastlines(color='#969696')
    ax.gridlines()

    # MCSs
    sc = plt.contour(data_moaap['lon'],
                        data_moaap['lat'],
                        np.array(data_moaap['MCS_Tb_Objects'][tt,:,:]),
                        colors = '#33a02c')

    

    ax.set_extent([-180, 180, -90, 90], crs=ccrs.PlateCarree())

    # Set the title of the plot
    plt.title('Objects identied by MOAAP at '+str(time_datetime[tt])[:16])

    # create legend
    for ob in range(len(object_names)):
      plt.plot([],[], color = object_names[ob][1], \
               linestyle = object_names[ob][2],\
               lw = object_names[ob][3],\
               label = object_names[ob][0])

    # plt.legend()
    ax.legend(bbox_to_anchor=(1, 0.00), ncol=4)


    # Show the plot
    fig.savefig('images/'+str(tt).zfill(3)+'_CausesOfExtreme_100_daily-extremes.jpg', bbox_inches='tight', dpi=100)
    plt.close()

import glob

from PIL import Image
def make_gif(frame_folder):
    frames = [Image.open(image) for image in np.sort(glob.glob(f"{frame_folder}/*.jpg"))]
    frame_one = frames[0]
    frame_one.save("phenomenon.gif", format="GIF", append_images=frames,
               save_all=True, duration=100, loop=0)

# if __name__ == "__main__":
make_gif("images/")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from IPython import display
# gifPath = Path("phenomenon.gif") # please paste the whole path from Step 2-6
# Display GIF in Jupyter, CoLab, IPython
with open("phenomenon.gif",'rb') as f:
    display.Image(data=f.read(), format='jpg')

from IPython.display import Image
fname = '/afs/ictp.it/home/m/mda_silv/Downloads/phenomenon.gif'
Image(open(fname, 'rb').read())

