#!/bin/bash

#SBATCH -A CMPNS_ictpclim
#SBATCH -p dcgp_usr_prod
#SBATCH -N 12
#SBATCH --ntasks-per-node=112
#SBATCH -t 1-00:00:00
#SBATCH -o logs/MODEL_SLURM.out
#SBATCH -e logs/MODEL_SLURM.err
#SBATCH -J Otis_ctrl
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=mda_silv@ictp.it

{
set -eo pipefail

# load required modules
# module purge
source /leonardo/home/userexternal/ggiulian/modules

NAMELIST=/leonardo/home/userexternal/mdasilva/github_projects/shell/ictp/regcm_exp/workshop2025/ctrl/RegCM5-ERA5_Otis_ctrl.in
BINARIES=/leonardo/home/userexternal/ggiulian/RegCM/bin/
EXTENSION=CLM45

# run model
mpirun $BINARIES/regcmMPI$EXTENSION $NAMELIST

}
