#!/bin/bash

#SBATCH -A ICT25_ESP
#SBATCH -p dcgp_usr_prod
#SBATCH -N 16 
#SBATCH --ntasks-per-node=112
#SBATCH -t 1-00:00:00
#SBATCH -o logs/WDM7-Europe.out
#SBATCH -e logs/WDM7-Europe.err
#SBATCH -J WDM7-Europe
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=mda_silv@ictp.it

{
set -eo pipefail

# load required modules
# module purge
source /leonardo/home/userexternal/ggiulian/modules

NAMELIST=/leonardo/home/userexternal/mdasilva/github_projects/shell/ictp/regcm_exp/eur_11/leonardo/EUR-11_WDM7.in
BINARIES=/leonardo/home/userexternal/mdasilva/RegCM/bin/
EXTENSION=CLM45

# run model
mpirun $BINARIES/regcmMPI$EXTENSION $NAMELIST
}
