'reinit'
'sdfopen mask_SAM.nc'
'set lat -15 36'
'set lon 21 66'
'set gxout fwrite'
'set fwrite -le mask_SAM_new.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'reinit'

*'open mask.ctl'
*'d mask'
*'set lat -30'
*'d mask'
