'reinit'
'sdfopen mask.nc'
'set lat -34.5 -15'
'set lon -76 -38.5'
'set gxout fwrite'
'set fwrite -le mask.gra'
'define mask=const(const(maskout(land,land-1),0),1,-u)'
'd mask'
'disable fwrite'
'reinit'

*'open mask.ctl'
*'d mask'
*'set lat -30'
*'d mask'
